### ISSUE TITLE
SqlToyLazyDao接口中的load方法日志打印两遍

### ISSUE THREAD

**Issue by canyuexiyang** [chenrenfei/sagacity-sqltoy#6]
您好。我使用SqlToyLazyDao接口中的load方法，根据主键进行查询，日志打印了两遍，如下图，请问是执行了两遍sql还单纯的日志打印了两遍。我自己查看过源码，没看出是什么问题，想请问一下您。
![image](https://user-images.githubusercontent.com/34767852/61506029-62312800-aa13-11e9-8081-e541ad7bfd58.png)

**Comment by canyuexiyang** [comment]
补充：SqlToy的version：4.2.15

**Comment by chenrenfei** [comment]
4.3.11 开始已经对日志进行了较大规模的梳理，4.5.x版本 基本已经清理完毕，目前正在测试4.5.3版本，增强泛型转换，避免每次(VO) load(); 每次转换功能。建议升级版本4.5.2版本

**Comment by chenrenfei** [comment]
之前日志是存在重复打印的情况的，在内部执行时又打印了一次

**Comment by canyuexiyang** [comment]
谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。

**Comment by 18521517002** [comment]
对象好像直接映射


------------------ 原始邮件 ------------------
发件人: "丶纯净水"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 下午3:40
收件人: "chenrenfei/sagacity-sqltoy"<sagacity-sqltoy@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6)




谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。

**Comment by canyuexiyang** [comment]
> 对象好像直接映射
> [...](#)
> ------------------ 原始邮件 ------------------ 发件人: "丶纯净水"<notifications@github.com>; 发送时间: 2019年7月19日(星期五) 下午3:40 收件人: "chenrenfei/sagacity-sqltoy"<sagacity-sqltoy@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

不是很明白你的意思。或者我描述的不是很清楚。我想表达的是，有没有一个修改某条记录之后，返回这条记录修改之后的值，不只是返回修改的这一个字段，而是这条记录的所有字段

**Comment by chenrenfei** [comment]
fetchUpdate 方法



zhongxuchen@gmail.com
 
发件人： 丶纯净水
发送时间： 2019-07-19 16:11
收件人： chenrenfei/sagacity-sqltoy
抄送： zhongxuchen; Comment
主题： Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6)
对象好像直接映射
...
------------------ 原始邮件 ------------------ 发件人: "丶纯净水"notifications@github.com; 发送时间: 2019年7月19日(星期五) 下午3:40 收件人: "chenrenfei/sagacity-sqltoy"sagacity-sqltoy@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
不是很明白你的意思。或者我描述的不是很清楚。我想表达的是，有没有一个修改某条记录之后，返回这条记录修改之后的值，不只是返回修改的这一个字段，而是这条记录的所有字段

**Comment by chenrenfei** [comment]
请参见：
updateFetch 方法，可以更改并返回变更后的结果，这个是基于jdbc内部协议来实现的，但必须自己写update的反调函数，请参见文档里面的说明



zhongxuchen@gmail.com
 
发件人： 丶纯净水
发送时间： 2019-07-19 16:11
收件人： chenrenfei/sagacity-sqltoy
抄送： zhongxuchen; Comment
主题： Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6)
对象好像直接映射
...
------------------ 原始邮件 ------------------ 发件人: "丶纯净水"notifications@github.com; 发送时间: 2019年7月19日(星期五) 下午3:40 收件人: "chenrenfei/sagacity-sqltoy"sagacity-sqltoy@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
不是很明白你的意思。或者我描述的不是很清楚。我想表达的是，有没有一个修改某条记录之后，返回这条记录修改之后的值，不只是返回修改的这一个字段，而是这条记录的所有字段

**Comment by canyuexiyang** [comment]
> 请参见： updateFetch 方法，可以更改并返回变更后的结果，这个是基于jdbc内部协议来实现的，但必须自己写update的反调函数，请参见文档里面的说明 zhongxuchen@gmail.com 发件人： 丶纯净水 发送时间： 2019-07-19 16:11 收件人： chenrenfei/sagacity-sqltoy 抄送： zhongxuchen; Comment 主题： Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 对象好像直接映射 ... ------------------ 原始邮件 ------------------ 发件人: "丶纯净水"notifications@github.com; 发送时间: 2019年7月19日(星期五) 下午3:40 收件人: "chenrenfei/sagacity-sqltoy"sagacity-sqltoy@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 不是很明白你的意思。或者我描述的不是很清楚。我想表达的是，有没有一个修改某条记录之后，返回这条记录修改之后的值，不只是返回修改的这一个字段，而是这条记录的所有字段 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

好的，谢谢您

**Comment by chenrenfei** [comment]
zhongxuchen@gmail.com
 
发件人： 丶纯净水
发送时间： 2019-07-19 16:31
收件人： chenrenfei/sagacity-sqltoy
抄送： zhongxuchen; Comment
主题： Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6)
请参见： updateFetch 方法，可以更改并返回变更后的结果，这个是基于jdbc内部协议来实现的，但必须自己写update的反调函数，请参见文档里面的说明 zhongxuchen@gmail.com 发件人： 丶纯净水 发送时间： 2019-07-19 16:11 收件人： chenrenfei/sagacity-sqltoy 抄送： zhongxuchen; Comment 主题： Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 对象好像直接映射 ... ------------------ 原始邮件 ------------------ 发件人: "丶纯净水"notifications@github.com; 发送时间: 2019年7月19日(星期五) 下午3:40 收件人: "chenrenfei/sagacity-sqltoy"sagacity-sqltoy@noreply.github.com; 抄送: "Subscribed"subscribed@noreply.github.com; 主题: Re: [chenrenfei/sagacity-sqltoy] SqlToyLazyDao接口中的load方法日志打印两遍 (#6) 谢谢，升级之后，日志确实没有打印两遍。还有一个不是问题的问题，就是，SqlToyLazyDao中的update方法返回的是受影响的行数，请问有没有修改记录之后，返回VO的方法呢？我现在的做法就是update之后，再根据主键，load一遍。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread. 不是很明白你的意思。或者我描述的不是很清楚。我想表达的是，有没有一个修改某条记录之后，返回这条记录修改之后的值，不只是返回修改的这一个字段，而是这条记录的所有字段 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
好的，谢谢您
